ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/almog1099/helloalmog'
  tag: 'chart_v1'
  pathliveness: /health/liveliness
  pathreadiness: /health/readiness

service:
  servicePort: 8080
probes:
  readiness:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  volume:
    mount:
      path: /tmp/html
test: Healthy